# Generated by Django 4.2.5 on 2023-09-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('insurance', models.CharField(default='ندارد', max_length=100)),
                ('supplier', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=250)),
                ('dateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
