# Generated by Django 4.2.5 on 2023-11-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewlerApp', '0003_sourceproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceproduct',
            name='identifier',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sourceproduct',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
