# Generated by Django 4.2.5 on 2023-11-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewlerApp', '0005_alter_sourceproduct_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identifier',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
